package oracle.apps.sfc.clm.PaymentApproval.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CLMApprovalStatusLovVORowImpl extends OAViewRowImpl {
    public static final int STATUSID = 0;
    public static final int STATUSNAME = 1;

    /**This is the default constructor (do not remove)
     */
    public CLMApprovalStatusLovVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute StatusId
     */
    public Number getStatusId() {
        return (Number) getAttributeInternal(STATUSID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusId
     */
    public void setStatusId(Number value) {
        setAttributeInternal(STATUSID, value);
    }

    /**Gets the attribute value for the calculated attribute StatusName
     */
    public String getStatusName() {
        return (String) getAttributeInternal(STATUSNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusName
     */
    public void setStatusName(String value) {
        setAttributeInternal(STATUSNAME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case STATUSID:
            return getStatusId();
        case STATUSNAME:
            return getStatusName();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case STATUSID:
            setStatusId((Number)value);
            return;
        case STATUSNAME:
            setStatusName((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
