package oracle.apps.sfc.clm.PaymentApproval.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CLMInvDetailsVORowImpl extends OAViewRowImpl {
    public static final int ROWID1 = 0;
    public static final int BANDWIDHREQID = 1;
    public static final int CLMID = 2;
    public static final int POHDRID = 3;
    public static final int PONUMBER = 4;
    public static final int POLINEID = 5;
    public static final int POLINENUMBER = 6;
    public static final int INVOICEDATE = 7;
    public static final int INVOICEAMOUNT = 8;
    public static final int TAXAMT = 9;
    public static final int TOTALAMOUNT = 10;
    public static final int ATTRIBUTE1 = 11;
    public static final int ATTRIBUTE2 = 12;
    public static final int ATTRIBUTE3 = 13;
    public static final int ATTRIBUTE4 = 14;
    public static final int ATTRIBUTE5 = 15;
    public static final int ATTRIBUTE6 = 16;
    public static final int ATTRIBUTE7 = 17;
    public static final int ATTRIBUTE8 = 18;
    public static final int ATTRIBUTE9 = 19;
    public static final int ATTRIBUTE10 = 20;
    public static final int ATTRIBUTE11 = 21;
    public static final int ATTRIBUTE12 = 22;
    public static final int ATTRIBUTE13 = 23;
    public static final int ATTRIBUTE14 = 24;
    public static final int ATTRIBUTE15 = 25;
    public static final int CREATIONDATE = 26;
    public static final int CREATEDBY = 27;
    public static final int LASTUPDATEDATE = 28;
    public static final int LASTUPDATEDBY = 29;
    public static final int LASTUPDATELOGIN = 30;
    public static final int POAPPROVALSTATUS = 31;
    public static final int INVOICESTATUS = 32;
    public static final int INVOICEWFSTATUS = 33;
    public static final int CLMINVOICEID = 34;
    public static final int CLMINVOICENUMBER = 35;
    public static final int EBSINVOICENUMBER = 36;
    public static final int EBSINVOICEID = 37;
    public static final int CLMPAYMENTHDRID = 38;
    public static final int CLMINVOICELINENO = 39;
    public static final int FROMLOCATION = 40;
    public static final int TOLOCATION = 41;
    public static final int ITEMKEY = 42;
    public static final int APPROVER1 = 43;
    public static final int APPROVER2 = 44;
    public static final int SAVEFLAG = 45;
    public static final int ERRORMSG = 46;
    public static final int CONCPROGRAMID = 47;
    public static final int INVOICEHDRID = 48;
    public static final int INVPERIODFROMDATE = 49;
    public static final int INVPERIODTODATE = 50;
    public static final int CIRCUITID = 51;
    public static final int POUOM = 52;
    public static final int POTAX = 53;
    public static final int ITEMCODE = 54;
    public static final int SUPPLIER = 55;
    public static final int SUPPLIERSITE = 56;
    public static final int ITEMID = 57;
    public static final int ITEMTYPE = 58;
    public static final int VENDORID = 59;
    public static final int VENDORSITEID = 60;
    public static final int POVALIDFROM = 61;
    public static final int POVALIDTO = 62;
    public static final int COMMISSIONEDDATE = 63;
    public static final int CAPACITY = 64;
    public static final int CONVERSIONRATE = 65;
    public static final int CHARGEACCOUNT = 66;
    public static final int POAMOUNT = 67;
    public static final int POLINEAMOUNT = 68;
    public static final int AMOUNTPAID = 69;
    public static final int BALAMT = 70;
    public static final int INVOICETYPE = 71;
    public static final int ADVPERIOD = 72;
    public static final int ADVAMOUNT = 73;
    public static final int ADVCURRENCY = 74;
    public static final int ADVSUPINVOICENO = 75;
    public static final int ADVSUPINVOICEDATE = 76;
    public static final int ADVVERIFIED = 77;
    public static final int ADVCREATEINVOICE = 78;
    public static final int ADVINVOICENO = 79;
    public static final int ACTIVITY = 80;
    public static final int LINKTYPE = 81;
    public static final int SURRENDEREDDATE = 82;
    public static final int PROCOMMISSIONEDDATE = 83;
    public static final int REMARKS = 84;
    public static final int DISTCODECOMBINATIONID = 85;
    public static final int ADVTAXPERCENT = 86;
    public static final int FROMLOCSNO = 87;
    public static final int TOLOCSNO = 88;
    public static final int ADVREMARKS = 89;
    public static final int LASTINVOICEDATE = 90;
    public static final int FINALSTATUS = 91;
    public static final int CLMCREATIONDATE = 92;
    public static final int VENDORSITECURRENCYCODE = 93;
    public static final int APPROVEDDATE = 94;
    public static final int BWDISTANCE = 95;
    public static final int BANDWIDHREQNO = 96;
    public static final int QTY = 97;
    public static final int ADVSTATUS = 98;
    public static final int PAYMENTSTATUS = 99;
    public static final int PAIDDATE = 100;
    public static final int PAYMENTDETAILS = 101;
    public static final int PAYMENTID = 102;
    public static final int EBSPONUMBER = 103;
    public static final int CLMPONUMBER = 104;
    public static final int EBSPOHEADERID = 105;
    public static final int EBSPOLINEID = 106;
    public static final int ITEMDESC = 107;
    public static final int PAYMENTTERM = 108;
    public static final int INVAMTREF = 109;
    public static final int BATCHNO = 110;
    public static final int CGSTTAXCODE = 111;
    public static final int SGSTTAXCODE = 112;
    public static final int IGSTTAXCODE = 113;
    public static final int CGSTTAXPER = 114;
    public static final int SGSTTAXPER = 115;
    public static final int IGSTTAXPER = 116;
    public static final int CGSTTAXAMT = 117;
    public static final int SGSTTAXAMT = 118;
    public static final int IGSTTAXAMT = 119;
    public static final int STGBATCHID = 120;
    public static final int INVOICETOLERANCE = 121;
    public static final int INVOICEPAYCYCLE = 122;
    public static final int INVOICECYCLESTATUS = 123;
    public static final int REJECTIONREASON = 124;
    public static final int APPROVER1DATE = 125;
    public static final int APPROVER2DATE = 126;
    public static final int FILEID = 127;
    public static final int ATTACHEDFILENAME = 128;
    public static final int ATTACHEDFILE = 129;
    public static final int CONTENTTYPE = 130;
    public static final int FACREATIONDATE = 131;
    public static final int FACREATEDBY = 132;
    public static final int FALASTUPDATEDATE = 133;
    public static final int FALASTUPDATEDBY = 134;
    public static final int FALASTUPDATELOGIN = 135;

    /**This is the default constructor (do not remove)
     */
    public CLMInvDetailsVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute RowId1
     */
    public RowID getRowId1() {
        return (RowID) getAttributeInternal(ROWID1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RowId1
     */
    public void setRowId1(RowID value) {
        setAttributeInternal(ROWID1, value);
    }

    /**Gets the attribute value for the calculated attribute BandWidhReqId
     */
    public String getBandWidhReqId() {
        return (String) getAttributeInternal(BANDWIDHREQID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BandWidhReqId
     */
    public void setBandWidhReqId(String value) {
        setAttributeInternal(BANDWIDHREQID, value);
    }

    /**Gets the attribute value for the calculated attribute ClmId
     */
    public Number getClmId() {
        return (Number) getAttributeInternal(CLMID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ClmId
     */
    public void setClmId(Number value) {
        setAttributeInternal(CLMID, value);
    }

    /**Gets the attribute value for the calculated attribute PoHdrId
     */
    public Number getPoHdrId() {
        return (Number) getAttributeInternal(POHDRID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoHdrId
     */
    public void setPoHdrId(Number value) {
        setAttributeInternal(POHDRID, value);
    }

    /**Gets the attribute value for the calculated attribute PoNumber
     */
    public String getPoNumber() {
        return (String) getAttributeInternal(PONUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoNumber
     */
    public void setPoNumber(String value) {
        setAttributeInternal(PONUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute PoLineId
     */
    public Number getPoLineId() {
        return (Number) getAttributeInternal(POLINEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoLineId
     */
    public void setPoLineId(Number value) {
        setAttributeInternal(POLINEID, value);
    }

    /**Gets the attribute value for the calculated attribute PoLineNumber
     */
    public Number getPoLineNumber() {
        return (Number) getAttributeInternal(POLINENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoLineNumber
     */
    public void setPoLineNumber(Number value) {
        setAttributeInternal(POLINENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceDate
     */
    public Date getInvoiceDate() {
        return (Date) getAttributeInternal(INVOICEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceDate
     */
    public void setInvoiceDate(Date value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceAmount
     */
    public Number getInvoiceAmount() {
        return (Number) getAttributeInternal(INVOICEAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceAmount
     */
    public void setInvoiceAmount(Number value) {
        setAttributeInternal(INVOICEAMOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute TaxAmt
     */
    public Number getTaxAmt() {
        return (Number) getAttributeInternal(TAXAMT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TaxAmt
     */
    public void setTaxAmt(Number value) {
        setAttributeInternal(TAXAMT, value);
    }

    /**Gets the attribute value for the calculated attribute TotalAmount
     */
    public Number getTotalAmount() {
        return (Number) getAttributeInternal(TOTALAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TotalAmount
     */
    public void setTotalAmount(Number value) {
        setAttributeInternal(TOTALAMOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute PoApprovalStatus
     */
    public String getPoApprovalStatus() {
        return (String) getAttributeInternal(POAPPROVALSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoApprovalStatus
     */
    public void setPoApprovalStatus(String value) {
        setAttributeInternal(POAPPROVALSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceStatus
     */
    public String getInvoiceStatus() {
        return (String) getAttributeInternal(INVOICESTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceStatus
     */
    public void setInvoiceStatus(String value) {
        setAttributeInternal(INVOICESTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceWfStatus
     */
    public String getInvoiceWfStatus() {
        return (String) getAttributeInternal(INVOICEWFSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceWfStatus
     */
    public void setInvoiceWfStatus(String value) {
        setAttributeInternal(INVOICEWFSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute ClmInvoiceId
     */
    public Number getClmInvoiceId() {
        return (Number) getAttributeInternal(CLMINVOICEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ClmInvoiceId
     */
    public void setClmInvoiceId(Number value) {
        setAttributeInternal(CLMINVOICEID, value);
    }

    /**Gets the attribute value for the calculated attribute ClmInvoiceNumber
     */
    public String getClmInvoiceNumber() {
        return (String) getAttributeInternal(CLMINVOICENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ClmInvoiceNumber
     */
    public void setClmInvoiceNumber(String value) {
        setAttributeInternal(CLMINVOICENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute EbsInvoiceNumber
     */
    public String getEbsInvoiceNumber() {
        return (String) getAttributeInternal(EBSINVOICENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EbsInvoiceNumber
     */
    public void setEbsInvoiceNumber(String value) {
        setAttributeInternal(EBSINVOICENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute EbsInvoiceId
     */
    public Number getEbsInvoiceId() {
        return (Number) getAttributeInternal(EBSINVOICEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EbsInvoiceId
     */
    public void setEbsInvoiceId(Number value) {
        setAttributeInternal(EBSINVOICEID, value);
    }

    /**Gets the attribute value for the calculated attribute ClmPaymentHdrId
     */
    public Number getClmPaymentHdrId() {
        return (Number) getAttributeInternal(CLMPAYMENTHDRID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ClmPaymentHdrId
     */
    public void setClmPaymentHdrId(Number value) {
        setAttributeInternal(CLMPAYMENTHDRID, value);
    }

    /**Gets the attribute value for the calculated attribute ClmInvoiceLineNo
     */
    public Number getClmInvoiceLineNo() {
        return (Number) getAttributeInternal(CLMINVOICELINENO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ClmInvoiceLineNo
     */
    public void setClmInvoiceLineNo(Number value) {
        setAttributeInternal(CLMINVOICELINENO, value);
    }

    /**Gets the attribute value for the calculated attribute FromLocation
     */
    public String getFromLocation() {
        return (String) getAttributeInternal(FROMLOCATION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FromLocation
     */
    public void setFromLocation(String value) {
        setAttributeInternal(FROMLOCATION, value);
    }

    /**Gets the attribute value for the calculated attribute ToLocation
     */
    public String getToLocation() {
        return (String) getAttributeInternal(TOLOCATION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ToLocation
     */
    public void setToLocation(String value) {
        setAttributeInternal(TOLOCATION, value);
    }

    /**Gets the attribute value for the calculated attribute ItemKey
     */
    public String getItemKey() {
        return (String) getAttributeInternal(ITEMKEY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ItemKey
     */
    public void setItemKey(String value) {
        setAttributeInternal(ITEMKEY, value);
    }

    /**Gets the attribute value for the calculated attribute Approver1
     */
    public String getApprover1() {
        return (String) getAttributeInternal(APPROVER1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Approver1
     */
    public void setApprover1(String value) {
        setAttributeInternal(APPROVER1, value);
    }

    /**Gets the attribute value for the calculated attribute Approver2
     */
    public String getApprover2() {
        return (String) getAttributeInternal(APPROVER2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Approver2
     */
    public void setApprover2(String value) {
        setAttributeInternal(APPROVER2, value);
    }

    /**Gets the attribute value for the calculated attribute SaveFlag
     */
    public String getSaveFlag() {
        return (String) getAttributeInternal(SAVEFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SaveFlag
     */
    public void setSaveFlag(String value) {
        setAttributeInternal(SAVEFLAG, value);
    }

    /**Gets the attribute value for the calculated attribute ErrorMsg
     */
    public String getErrorMsg() {
        return (String) getAttributeInternal(ERRORMSG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ErrorMsg
     */
    public void setErrorMsg(String value) {
        setAttributeInternal(ERRORMSG, value);
    }

    /**Gets the attribute value for the calculated attribute ConcProgramId
     */
    public Number getConcProgramId() {
        return (Number) getAttributeInternal(CONCPROGRAMID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ConcProgramId
     */
    public void setConcProgramId(Number value) {
        setAttributeInternal(CONCPROGRAMID, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceHdrId
     */
    public Number getInvoiceHdrId() {
        return (Number) getAttributeInternal(INVOICEHDRID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceHdrId
     */
    public void setInvoiceHdrId(Number value) {
        setAttributeInternal(INVOICEHDRID, value);
    }

    /**Gets the attribute value for the calculated attribute InvPeriodFromDate
     */
    public Date getInvPeriodFromDate() {
        return (Date) getAttributeInternal(INVPERIODFROMDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvPeriodFromDate
     */
    public void setInvPeriodFromDate(Date value) {
        setAttributeInternal(INVPERIODFROMDATE, value);
    }

    /**Gets the attribute value for the calculated attribute InvPeriodToDate
     */
    public Date getInvPeriodToDate() {
        return (Date) getAttributeInternal(INVPERIODTODATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvPeriodToDate
     */
    public void setInvPeriodToDate(Date value) {
        setAttributeInternal(INVPERIODTODATE, value);
    }

    /**Gets the attribute value for the calculated attribute CircuitId
     */
    public String getCircuitId() {
        return (String) getAttributeInternal(CIRCUITID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CircuitId
     */
    public void setCircuitId(String value) {
        setAttributeInternal(CIRCUITID, value);
    }

    /**Gets the attribute value for the calculated attribute PoUom
     */
    public String getPoUom() {
        return (String) getAttributeInternal(POUOM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoUom
     */
    public void setPoUom(String value) {
        setAttributeInternal(POUOM, value);
    }

    /**Gets the attribute value for the calculated attribute PoTax
     */
    public Number getPoTax() {
        return (Number) getAttributeInternal(POTAX);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoTax
     */
    public void setPoTax(Number value) {
        setAttributeInternal(POTAX, value);
    }

    /**Gets the attribute value for the calculated attribute ItemCode
     */
    public String getItemCode() {
        return (String) getAttributeInternal(ITEMCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Supplier
     */
    public String getSupplier() {
        return (String) getAttributeInternal(SUPPLIER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Supplier
     */
    public void setSupplier(String value) {
        setAttributeInternal(SUPPLIER, value);
    }

    /**Gets the attribute value for the calculated attribute SupplierSite
     */
    public String getSupplierSite() {
        return (String) getAttributeInternal(SUPPLIERSITE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SupplierSite
     */
    public void setSupplierSite(String value) {
        setAttributeInternal(SUPPLIERSITE, value);
    }

    /**Gets the attribute value for the calculated attribute ItemId
     */
    public Number getItemId() {
        return (Number) getAttributeInternal(ITEMID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ItemId
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**Gets the attribute value for the calculated attribute ItemType
     */
    public String getItemType() {
        return (String) getAttributeInternal(ITEMTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ItemType
     */
    public void setItemType(String value) {
        setAttributeInternal(ITEMTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute VendorId
     */
    public Number getVendorId() {
        return (Number) getAttributeInternal(VENDORID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorId
     */
    public void setVendorId(Number value) {
        setAttributeInternal(VENDORID, value);
    }

    /**Gets the attribute value for the calculated attribute VendorSiteId
     */
    public Number getVendorSiteId() {
        return (Number) getAttributeInternal(VENDORSITEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorSiteId
     */
    public void setVendorSiteId(Number value) {
        setAttributeInternal(VENDORSITEID, value);
    }

    /**Gets the attribute value for the calculated attribute PoValidFrom
     */
    public Date getPoValidFrom() {
        return (Date) getAttributeInternal(POVALIDFROM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoValidFrom
     */
    public void setPoValidFrom(Date value) {
        setAttributeInternal(POVALIDFROM, value);
    }

    /**Gets the attribute value for the calculated attribute PoValidTo
     */
    public Date getPoValidTo() {
        return (Date) getAttributeInternal(POVALIDTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoValidTo
     */
    public void setPoValidTo(Date value) {
        setAttributeInternal(POVALIDTO, value);
    }

    /**Gets the attribute value for the calculated attribute CommissionedDate
     */
    public Date getCommissionedDate() {
        return (Date) getAttributeInternal(COMMISSIONEDDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CommissionedDate
     */
    public void setCommissionedDate(Date value) {
        setAttributeInternal(COMMISSIONEDDATE, value);
    }

    /**Gets the attribute value for the calculated attribute Capacity
     */
    public String getCapacity() {
        return (String) getAttributeInternal(CAPACITY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Capacity
     */
    public void setCapacity(String value) {
        setAttributeInternal(CAPACITY, value);
    }

    /**Gets the attribute value for the calculated attribute ConversionRate
     */
    public Number getConversionRate() {
        return (Number) getAttributeInternal(CONVERSIONRATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ConversionRate
     */
    public void setConversionRate(Number value) {
        setAttributeInternal(CONVERSIONRATE, value);
    }

    /**Gets the attribute value for the calculated attribute ChargeAccount
     */
    public String getChargeAccount() {
        return (String) getAttributeInternal(CHARGEACCOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ChargeAccount
     */
    public void setChargeAccount(String value) {
        setAttributeInternal(CHARGEACCOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute PoAmount
     */
    public Number getPoAmount() {
        return (Number) getAttributeInternal(POAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoAmount
     */
    public void setPoAmount(Number value) {
        setAttributeInternal(POAMOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute PoLineAmount
     */
    public Number getPoLineAmount() {
        return (Number) getAttributeInternal(POLINEAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoLineAmount
     */
    public void setPoLineAmount(Number value) {
        setAttributeInternal(POLINEAMOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute AmountPaid
     */
    public Number getAmountPaid() {
        return (Number) getAttributeInternal(AMOUNTPAID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AmountPaid
     */
    public void setAmountPaid(Number value) {
        setAttributeInternal(AMOUNTPAID, value);
    }

    /**Gets the attribute value for the calculated attribute BalAmt
     */
    public Number getBalAmt() {
        return (Number) getAttributeInternal(BALAMT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BalAmt
     */
    public void setBalAmt(Number value) {
        setAttributeInternal(BALAMT, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceType
     */
    public String getInvoiceType() {
        return (String) getAttributeInternal(INVOICETYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceType
     */
    public void setInvoiceType(String value) {
        setAttributeInternal(INVOICETYPE, value);
    }

    /**Gets the attribute value for the calculated attribute AdvPeriod
     */
    public String getAdvPeriod() {
        return (String) getAttributeInternal(ADVPERIOD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AdvPeriod
     */
    public void setAdvPeriod(String value) {
        setAttributeInternal(ADVPERIOD, value);
    }

    /**Gets the attribute value for the calculated attribute AdvAmount
     */
    public Number getAdvAmount() {
        return (Number) getAttributeInternal(ADVAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AdvAmount
     */
    public void setAdvAmount(Number value) {
        setAttributeInternal(ADVAMOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute AdvCurrency
     */
    public String getAdvCurrency() {
        return (String) getAttributeInternal(ADVCURRENCY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AdvCurrency
     */
    public void setAdvCurrency(String value) {
        setAttributeInternal(ADVCURRENCY, value);
    }

    /**Gets the attribute value for the calculated attribute AdvSupInvoiceNo
     */
    public String getAdvSupInvoiceNo() {
        return (String) getAttributeInternal(ADVSUPINVOICENO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AdvSupInvoiceNo
     */
    public void setAdvSupInvoiceNo(String value) {
        setAttributeInternal(ADVSUPINVOICENO, value);
    }

    /**Gets the attribute value for the calculated attribute AdvSupInvoiceDate
     */
    public Date getAdvSupInvoiceDate() {
        return (Date) getAttributeInternal(ADVSUPINVOICEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AdvSupInvoiceDate
     */
    public void setAdvSupInvoiceDate(Date value) {
        setAttributeInternal(ADVSUPINVOICEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute AdvVerified
     */
    public String getAdvVerified() {
        return (String) getAttributeInternal(ADVVERIFIED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AdvVerified
     */
    public void setAdvVerified(String value) {
        setAttributeInternal(ADVVERIFIED, value);
    }

    /**Gets the attribute value for the calculated attribute AdvCreateInvoice
     */
    public String getAdvCreateInvoice() {
        return (String) getAttributeInternal(ADVCREATEINVOICE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AdvCreateInvoice
     */
    public void setAdvCreateInvoice(String value) {
        setAttributeInternal(ADVCREATEINVOICE, value);
    }

    /**Gets the attribute value for the calculated attribute AdvInvoiceNo
     */
    public String getAdvInvoiceNo() {
        return (String) getAttributeInternal(ADVINVOICENO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AdvInvoiceNo
     */
    public void setAdvInvoiceNo(String value) {
        setAttributeInternal(ADVINVOICENO, value);
    }

    /**Gets the attribute value for the calculated attribute Activity
     */
    public String getActivity() {
        return (String) getAttributeInternal(ACTIVITY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Activity
     */
    public void setActivity(String value) {
        setAttributeInternal(ACTIVITY, value);
    }

    /**Gets the attribute value for the calculated attribute LinkType
     */
    public String getLinkType() {
        return (String) getAttributeInternal(LINKTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LinkType
     */
    public void setLinkType(String value) {
        setAttributeInternal(LINKTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute SurrenderedDate
     */
    public Date getSurrenderedDate() {
        return (Date) getAttributeInternal(SURRENDEREDDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SurrenderedDate
     */
    public void setSurrenderedDate(Date value) {
        setAttributeInternal(SURRENDEREDDATE, value);
    }

    /**Gets the attribute value for the calculated attribute ProCommissionedDate
     */
    public Date getProCommissionedDate() {
        return (Date) getAttributeInternal(PROCOMMISSIONEDDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProCommissionedDate
     */
    public void setProCommissionedDate(Date value) {
        setAttributeInternal(PROCOMMISSIONEDDATE, value);
    }

    /**Gets the attribute value for the calculated attribute Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**Gets the attribute value for the calculated attribute DistCodeCombinationId
     */
    public Number getDistCodeCombinationId() {
        return (Number) getAttributeInternal(DISTCODECOMBINATIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DistCodeCombinationId
     */
    public void setDistCodeCombinationId(Number value) {
        setAttributeInternal(DISTCODECOMBINATIONID, value);
    }

    /**Gets the attribute value for the calculated attribute AdvTaxPercent
     */
    public Number getAdvTaxPercent() {
        return (Number) getAttributeInternal(ADVTAXPERCENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AdvTaxPercent
     */
    public void setAdvTaxPercent(Number value) {
        setAttributeInternal(ADVTAXPERCENT, value);
    }

    /**Gets the attribute value for the calculated attribute FromLocSno
     */
    public Number getFromLocSno() {
        return (Number) getAttributeInternal(FROMLOCSNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FromLocSno
     */
    public void setFromLocSno(Number value) {
        setAttributeInternal(FROMLOCSNO, value);
    }

    /**Gets the attribute value for the calculated attribute ToLocSno
     */
    public Number getToLocSno() {
        return (Number) getAttributeInternal(TOLOCSNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ToLocSno
     */
    public void setToLocSno(Number value) {
        setAttributeInternal(TOLOCSNO, value);
    }

    /**Gets the attribute value for the calculated attribute AdvRemarks
     */
    public String getAdvRemarks() {
        return (String) getAttributeInternal(ADVREMARKS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AdvRemarks
     */
    public void setAdvRemarks(String value) {
        setAttributeInternal(ADVREMARKS, value);
    }

    /**Gets the attribute value for the calculated attribute LastInvoiceDate
     */
    public Date getLastInvoiceDate() {
        return (Date) getAttributeInternal(LASTINVOICEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastInvoiceDate
     */
    public void setLastInvoiceDate(Date value) {
        setAttributeInternal(LASTINVOICEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute FinalStatus
     */
    public String getFinalStatus() {
        return (String) getAttributeInternal(FINALSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FinalStatus
     */
    public void setFinalStatus(String value) {
        setAttributeInternal(FINALSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute ClmCreationDate
     */
    public Date getClmCreationDate() {
        return (Date) getAttributeInternal(CLMCREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ClmCreationDate
     */
    public void setClmCreationDate(Date value) {
        setAttributeInternal(CLMCREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute VendorSiteCurrencyCode
     */
    public String getVendorSiteCurrencyCode() {
        return (String) getAttributeInternal(VENDORSITECURRENCYCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorSiteCurrencyCode
     */
    public void setVendorSiteCurrencyCode(String value) {
        setAttributeInternal(VENDORSITECURRENCYCODE, value);
    }

    /**Gets the attribute value for the calculated attribute ApprovedDate
     */
    public Date getApprovedDate() {
        return (Date) getAttributeInternal(APPROVEDDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ApprovedDate
     */
    public void setApprovedDate(Date value) {
        setAttributeInternal(APPROVEDDATE, value);
    }

    /**Gets the attribute value for the calculated attribute BwDistance
     */
    public Number getBwDistance() {
        return (Number) getAttributeInternal(BWDISTANCE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BwDistance
     */
    public void setBwDistance(Number value) {
        setAttributeInternal(BWDISTANCE, value);
    }

    /**Gets the attribute value for the calculated attribute BandWidhReqNo
     */
    public String getBandWidhReqNo() {
        return (String) getAttributeInternal(BANDWIDHREQNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BandWidhReqNo
     */
    public void setBandWidhReqNo(String value) {
        setAttributeInternal(BANDWIDHREQNO, value);
    }

    /**Gets the attribute value for the calculated attribute Qty
     */
    public Number getQty() {
        return (Number) getAttributeInternal(QTY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Qty
     */
    public void setQty(Number value) {
        setAttributeInternal(QTY, value);
    }

    /**Gets the attribute value for the calculated attribute AdvStatus
     */
    public String getAdvStatus() {
        return (String) getAttributeInternal(ADVSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AdvStatus
     */
    public void setAdvStatus(String value) {
        setAttributeInternal(ADVSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute PaymentStatus
     */
    public String getPaymentStatus() {
        return (String) getAttributeInternal(PAYMENTSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PaymentStatus
     */
    public void setPaymentStatus(String value) {
        setAttributeInternal(PAYMENTSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute PaidDate
     */
    public Date getPaidDate() {
        return (Date) getAttributeInternal(PAIDDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PaidDate
     */
    public void setPaidDate(Date value) {
        setAttributeInternal(PAIDDATE, value);
    }

    /**Gets the attribute value for the calculated attribute PaymentDetails
     */
    public String getPaymentDetails() {
        return (String) getAttributeInternal(PAYMENTDETAILS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PaymentDetails
     */
    public void setPaymentDetails(String value) {
        setAttributeInternal(PAYMENTDETAILS, value);
    }

    /**Gets the attribute value for the calculated attribute PaymentId
     */
    public Number getPaymentId() {
        return (Number) getAttributeInternal(PAYMENTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PaymentId
     */
    public void setPaymentId(Number value) {
        setAttributeInternal(PAYMENTID, value);
    }

    /**Gets the attribute value for the calculated attribute EbsPoNumber
     */
    public Number getEbsPoNumber() {
        return (Number) getAttributeInternal(EBSPONUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EbsPoNumber
     */
    public void setEbsPoNumber(Number value) {
        setAttributeInternal(EBSPONUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute ClmPoNumber
     */
    public Number getClmPoNumber() {
        return (Number) getAttributeInternal(CLMPONUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ClmPoNumber
     */
    public void setClmPoNumber(Number value) {
        setAttributeInternal(CLMPONUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute EbsPoHeaderId
     */
    public Number getEbsPoHeaderId() {
        return (Number) getAttributeInternal(EBSPOHEADERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EbsPoHeaderId
     */
    public void setEbsPoHeaderId(Number value) {
        setAttributeInternal(EBSPOHEADERID, value);
    }

    /**Gets the attribute value for the calculated attribute EbsPoLineId
     */
    public Number getEbsPoLineId() {
        return (Number) getAttributeInternal(EBSPOLINEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EbsPoLineId
     */
    public void setEbsPoLineId(Number value) {
        setAttributeInternal(EBSPOLINEID, value);
    }

    /**Gets the attribute value for the calculated attribute ItemDesc
     */
    public String getItemDesc() {
        return (String) getAttributeInternal(ITEMDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ItemDesc
     */
    public void setItemDesc(String value) {
        setAttributeInternal(ITEMDESC, value);
    }

    /**Gets the attribute value for the calculated attribute PaymentTerm
     */
    public String getPaymentTerm() {
        return (String) getAttributeInternal(PAYMENTTERM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PaymentTerm
     */
    public void setPaymentTerm(String value) {
        setAttributeInternal(PAYMENTTERM, value);
    }

    /**Gets the attribute value for the calculated attribute InvAmtRef
     */
    public Number getInvAmtRef() {
        return (Number) getAttributeInternal(INVAMTREF);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvAmtRef
     */
    public void setInvAmtRef(Number value) {
        setAttributeInternal(INVAMTREF, value);
    }

    /**Gets the attribute value for the calculated attribute BatchNo
     */
    public Number getBatchNo() {
        return (Number) getAttributeInternal(BATCHNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BatchNo
     */
    public void setBatchNo(Number value) {
        setAttributeInternal(BATCHNO, value);
    }

    /**Gets the attribute value for the calculated attribute CgstTaxCode
     */
    public String getCgstTaxCode() {
        return (String) getAttributeInternal(CGSTTAXCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CgstTaxCode
     */
    public void setCgstTaxCode(String value) {
        setAttributeInternal(CGSTTAXCODE, value);
    }

    /**Gets the attribute value for the calculated attribute SgstTaxCode
     */
    public String getSgstTaxCode() {
        return (String) getAttributeInternal(SGSTTAXCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SgstTaxCode
     */
    public void setSgstTaxCode(String value) {
        setAttributeInternal(SGSTTAXCODE, value);
    }

    /**Gets the attribute value for the calculated attribute IgstTaxCode
     */
    public String getIgstTaxCode() {
        return (String) getAttributeInternal(IGSTTAXCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IgstTaxCode
     */
    public void setIgstTaxCode(String value) {
        setAttributeInternal(IGSTTAXCODE, value);
    }

    /**Gets the attribute value for the calculated attribute CgstTaxPer
     */
    public Number getCgstTaxPer() {
        return (Number) getAttributeInternal(CGSTTAXPER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CgstTaxPer
     */
    public void setCgstTaxPer(Number value) {
        setAttributeInternal(CGSTTAXPER, value);
    }

    /**Gets the attribute value for the calculated attribute SgstTaxPer
     */
    public Number getSgstTaxPer() {
        return (Number) getAttributeInternal(SGSTTAXPER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SgstTaxPer
     */
    public void setSgstTaxPer(Number value) {
        setAttributeInternal(SGSTTAXPER, value);
    }

    /**Gets the attribute value for the calculated attribute IgstTaxPer
     */
    public Number getIgstTaxPer() {
        return (Number) getAttributeInternal(IGSTTAXPER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IgstTaxPer
     */
    public void setIgstTaxPer(Number value) {
        setAttributeInternal(IGSTTAXPER, value);
    }

    /**Gets the attribute value for the calculated attribute CgstTaxAmt
     */
    public Number getCgstTaxAmt() {
        return (Number) getAttributeInternal(CGSTTAXAMT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CgstTaxAmt
     */
    public void setCgstTaxAmt(Number value) {
        setAttributeInternal(CGSTTAXAMT, value);
    }

    /**Gets the attribute value for the calculated attribute SgstTaxAmt
     */
    public Number getSgstTaxAmt() {
        return (Number) getAttributeInternal(SGSTTAXAMT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SgstTaxAmt
     */
    public void setSgstTaxAmt(Number value) {
        setAttributeInternal(SGSTTAXAMT, value);
    }

    /**Gets the attribute value for the calculated attribute IgstTaxAmt
     */
    public Number getIgstTaxAmt() {
        return (Number) getAttributeInternal(IGSTTAXAMT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IgstTaxAmt
     */
    public void setIgstTaxAmt(Number value) {
        setAttributeInternal(IGSTTAXAMT, value);
    }

    /**Gets the attribute value for the calculated attribute StgBatchId
     */
    public Number getStgBatchId() {
        return (Number) getAttributeInternal(STGBATCHID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StgBatchId
     */
    public void setStgBatchId(Number value) {
        setAttributeInternal(STGBATCHID, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceTolerance
     */
    public Number getInvoiceTolerance() {
        return (Number) getAttributeInternal(INVOICETOLERANCE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceTolerance
     */
    public void setInvoiceTolerance(Number value) {
        setAttributeInternal(INVOICETOLERANCE, value);
    }

    /**Gets the attribute value for the calculated attribute InvoicePayCycle
     */
    public Number getInvoicePayCycle() {
        return (Number) getAttributeInternal(INVOICEPAYCYCLE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoicePayCycle
     */
    public void setInvoicePayCycle(Number value) {
        setAttributeInternal(INVOICEPAYCYCLE, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceCycleStatus
     */
    public String getInvoiceCycleStatus() {
        return (String) getAttributeInternal(INVOICECYCLESTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceCycleStatus
     */
    public void setInvoiceCycleStatus(String value) {
        setAttributeInternal(INVOICECYCLESTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute RejectionReason
     */
    public String getRejectionReason() {
        return (String) getAttributeInternal(REJECTIONREASON);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RejectionReason
     */
    public void setRejectionReason(String value) {
        setAttributeInternal(REJECTIONREASON, value);
    }

    /**Gets the attribute value for the calculated attribute Approver1Date
     */
    public Date getApprover1Date() {
        return (Date) getAttributeInternal(APPROVER1DATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Approver1Date
     */
    public void setApprover1Date(Date value) {
        setAttributeInternal(APPROVER1DATE, value);
    }

    /**Gets the attribute value for the calculated attribute Approver2Date
     */
    public Date getApprover2Date() {
        return (Date) getAttributeInternal(APPROVER2DATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Approver2Date
     */
    public void setApprover2Date(Date value) {
        setAttributeInternal(APPROVER2DATE, value);
    }

    /**Gets the attribute value for the calculated attribute FileId
     */
    public String getFileId() {
        return (String) getAttributeInternal(FILEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FileId
     */
    public void setFileId(String value) {
        setAttributeInternal(FILEID, value);
    }

    /**Gets the attribute value for the calculated attribute AttachedFileName
     */
    public String getAttachedFileName() {
        return (String) getAttributeInternal(ATTACHEDFILENAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AttachedFileName
     */
    public void setAttachedFileName(String value) {
        setAttributeInternal(ATTACHEDFILENAME, value);
    }

    /**Gets the attribute value for the calculated attribute AttachedFile
     */
    public BlobDomain getAttachedFile() {
        return (BlobDomain) getAttributeInternal(ATTACHEDFILE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AttachedFile
     */
    public void setAttachedFile(BlobDomain value) {
        setAttributeInternal(ATTACHEDFILE, value);
    }

    /**Gets the attribute value for the calculated attribute Contenttype
     */
    public String getContenttype() {
        return (String) getAttributeInternal(CONTENTTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Contenttype
     */
    public void setContenttype(String value) {
        setAttributeInternal(CONTENTTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute FaCreationDate
     */
    public Date getFaCreationDate() {
        return (Date) getAttributeInternal(FACREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaCreationDate
     */
    public void setFaCreationDate(Date value) {
        setAttributeInternal(FACREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute FaCreatedBy
     */
    public Number getFaCreatedBy() {
        return (Number) getAttributeInternal(FACREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaCreatedBy
     */
    public void setFaCreatedBy(Number value) {
        setAttributeInternal(FACREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute FaLastUpdateDate
     */
    public Date getFaLastUpdateDate() {
        return (Date) getAttributeInternal(FALASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaLastUpdateDate
     */
    public void setFaLastUpdateDate(Date value) {
        setAttributeInternal(FALASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute FaLastUpdatedBy
     */
    public Number getFaLastUpdatedBy() {
        return (Number) getAttributeInternal(FALASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaLastUpdatedBy
     */
    public void setFaLastUpdatedBy(Number value) {
        setAttributeInternal(FALASTUPDATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute FaLastUpdateLogin
     */
    public Number getFaLastUpdateLogin() {
        return (Number) getAttributeInternal(FALASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaLastUpdateLogin
     */
    public void setFaLastUpdateLogin(Number value) {
        setAttributeInternal(FALASTUPDATELOGIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROWID1:
            return getRowId1();
        case BANDWIDHREQID:
            return getBandWidhReqId();
        case CLMID:
            return getClmId();
        case POHDRID:
            return getPoHdrId();
        case PONUMBER:
            return getPoNumber();
        case POLINEID:
            return getPoLineId();
        case POLINENUMBER:
            return getPoLineNumber();
        case INVOICEDATE:
            return getInvoiceDate();
        case INVOICEAMOUNT:
            return getInvoiceAmount();
        case TAXAMT:
            return getTaxAmt();
        case TOTALAMOUNT:
            return getTotalAmount();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        case ATTRIBUTE11:
            return getAttribute11();
        case ATTRIBUTE12:
            return getAttribute12();
        case ATTRIBUTE13:
            return getAttribute13();
        case ATTRIBUTE14:
            return getAttribute14();
        case ATTRIBUTE15:
            return getAttribute15();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case POAPPROVALSTATUS:
            return getPoApprovalStatus();
        case INVOICESTATUS:
            return getInvoiceStatus();
        case INVOICEWFSTATUS:
            return getInvoiceWfStatus();
        case CLMINVOICEID:
            return getClmInvoiceId();
        case CLMINVOICENUMBER:
            return getClmInvoiceNumber();
        case EBSINVOICENUMBER:
            return getEbsInvoiceNumber();
        case EBSINVOICEID:
            return getEbsInvoiceId();
        case CLMPAYMENTHDRID:
            return getClmPaymentHdrId();
        case CLMINVOICELINENO:
            return getClmInvoiceLineNo();
        case FROMLOCATION:
            return getFromLocation();
        case TOLOCATION:
            return getToLocation();
        case ITEMKEY:
            return getItemKey();
        case APPROVER1:
            return getApprover1();
        case APPROVER2:
            return getApprover2();
        case SAVEFLAG:
            return getSaveFlag();
        case ERRORMSG:
            return getErrorMsg();
        case CONCPROGRAMID:
            return getConcProgramId();
        case INVOICEHDRID:
            return getInvoiceHdrId();
        case INVPERIODFROMDATE:
            return getInvPeriodFromDate();
        case INVPERIODTODATE:
            return getInvPeriodToDate();
        case CIRCUITID:
            return getCircuitId();
        case POUOM:
            return getPoUom();
        case POTAX:
            return getPoTax();
        case ITEMCODE:
            return getItemCode();
        case SUPPLIER:
            return getSupplier();
        case SUPPLIERSITE:
            return getSupplierSite();
        case ITEMID:
            return getItemId();
        case ITEMTYPE:
            return getItemType();
        case VENDORID:
            return getVendorId();
        case VENDORSITEID:
            return getVendorSiteId();
        case POVALIDFROM:
            return getPoValidFrom();
        case POVALIDTO:
            return getPoValidTo();
        case COMMISSIONEDDATE:
            return getCommissionedDate();
        case CAPACITY:
            return getCapacity();
        case CONVERSIONRATE:
            return getConversionRate();
        case CHARGEACCOUNT:
            return getChargeAccount();
        case POAMOUNT:
            return getPoAmount();
        case POLINEAMOUNT:
            return getPoLineAmount();
        case AMOUNTPAID:
            return getAmountPaid();
        case BALAMT:
            return getBalAmt();
        case INVOICETYPE:
            return getInvoiceType();
        case ADVPERIOD:
            return getAdvPeriod();
        case ADVAMOUNT:
            return getAdvAmount();
        case ADVCURRENCY:
            return getAdvCurrency();
        case ADVSUPINVOICENO:
            return getAdvSupInvoiceNo();
        case ADVSUPINVOICEDATE:
            return getAdvSupInvoiceDate();
        case ADVVERIFIED:
            return getAdvVerified();
        case ADVCREATEINVOICE:
            return getAdvCreateInvoice();
        case ADVINVOICENO:
            return getAdvInvoiceNo();
        case ACTIVITY:
            return getActivity();
        case LINKTYPE:
            return getLinkType();
        case SURRENDEREDDATE:
            return getSurrenderedDate();
        case PROCOMMISSIONEDDATE:
            return getProCommissionedDate();
        case REMARKS:
            return getRemarks();
        case DISTCODECOMBINATIONID:
            return getDistCodeCombinationId();
        case ADVTAXPERCENT:
            return getAdvTaxPercent();
        case FROMLOCSNO:
            return getFromLocSno();
        case TOLOCSNO:
            return getToLocSno();
        case ADVREMARKS:
            return getAdvRemarks();
        case LASTINVOICEDATE:
            return getLastInvoiceDate();
        case FINALSTATUS:
            return getFinalStatus();
        case CLMCREATIONDATE:
            return getClmCreationDate();
        case VENDORSITECURRENCYCODE:
            return getVendorSiteCurrencyCode();
        case APPROVEDDATE:
            return getApprovedDate();
        case BWDISTANCE:
            return getBwDistance();
        case BANDWIDHREQNO:
            return getBandWidhReqNo();
        case QTY:
            return getQty();
        case ADVSTATUS:
            return getAdvStatus();
        case PAYMENTSTATUS:
            return getPaymentStatus();
        case PAIDDATE:
            return getPaidDate();
        case PAYMENTDETAILS:
            return getPaymentDetails();
        case PAYMENTID:
            return getPaymentId();
        case EBSPONUMBER:
            return getEbsPoNumber();
        case CLMPONUMBER:
            return getClmPoNumber();
        case EBSPOHEADERID:
            return getEbsPoHeaderId();
        case EBSPOLINEID:
            return getEbsPoLineId();
        case ITEMDESC:
            return getItemDesc();
        case PAYMENTTERM:
            return getPaymentTerm();
        case INVAMTREF:
            return getInvAmtRef();
        case BATCHNO:
            return getBatchNo();
        case CGSTTAXCODE:
            return getCgstTaxCode();
        case SGSTTAXCODE:
            return getSgstTaxCode();
        case IGSTTAXCODE:
            return getIgstTaxCode();
        case CGSTTAXPER:
            return getCgstTaxPer();
        case SGSTTAXPER:
            return getSgstTaxPer();
        case IGSTTAXPER:
            return getIgstTaxPer();
        case CGSTTAXAMT:
            return getCgstTaxAmt();
        case SGSTTAXAMT:
            return getSgstTaxAmt();
        case IGSTTAXAMT:
            return getIgstTaxAmt();
        case STGBATCHID:
            return getStgBatchId();
        case INVOICETOLERANCE:
            return getInvoiceTolerance();
        case INVOICEPAYCYCLE:
            return getInvoicePayCycle();
        case INVOICECYCLESTATUS:
            return getInvoiceCycleStatus();
        case REJECTIONREASON:
            return getRejectionReason();
        case APPROVER1DATE:
            return getApprover1Date();
        case APPROVER2DATE:
            return getApprover2Date();
        case FILEID:
            return getFileId();
        case ATTACHEDFILENAME:
            return getAttachedFileName();
        case ATTACHEDFILE:
            return getAttachedFile();
        case CONTENTTYPE:
            return getContenttype();
        case FACREATIONDATE:
            return getFaCreationDate();
        case FACREATEDBY:
            return getFaCreatedBy();
        case FALASTUPDATEDATE:
            return getFaLastUpdateDate();
        case FALASTUPDATEDBY:
            return getFaLastUpdatedBy();
        case FALASTUPDATELOGIN:
            return getFaLastUpdateLogin();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROWID1:
            setRowId1((RowID)value);
            return;
        case BANDWIDHREQID:
            setBandWidhReqId((String)value);
            return;
        case CLMID:
            setClmId((Number)value);
            return;
        case POHDRID:
            setPoHdrId((Number)value);
            return;
        case PONUMBER:
            setPoNumber((String)value);
            return;
        case POLINEID:
            setPoLineId((Number)value);
            return;
        case POLINENUMBER:
            setPoLineNumber((Number)value);
            return;
        case INVOICEDATE:
            setInvoiceDate((Date)value);
            return;
        case INVOICEAMOUNT:
            setInvoiceAmount((Number)value);
            return;
        case TAXAMT:
            setTaxAmt((Number)value);
            return;
        case TOTALAMOUNT:
            setTotalAmount((Number)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE8:
            setAttribute8((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case ATTRIBUTE11:
            setAttribute11((String)value);
            return;
        case ATTRIBUTE12:
            setAttribute12((String)value);
            return;
        case ATTRIBUTE13:
            setAttribute13((String)value);
            return;
        case ATTRIBUTE14:
            setAttribute14((String)value);
            return;
        case ATTRIBUTE15:
            setAttribute15((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case POAPPROVALSTATUS:
            setPoApprovalStatus((String)value);
            return;
        case INVOICESTATUS:
            setInvoiceStatus((String)value);
            return;
        case INVOICEWFSTATUS:
            setInvoiceWfStatus((String)value);
            return;
        case CLMINVOICEID:
            setClmInvoiceId((Number)value);
            return;
        case CLMINVOICENUMBER:
            setClmInvoiceNumber((String)value);
            return;
        case EBSINVOICENUMBER:
            setEbsInvoiceNumber((String)value);
            return;
        case EBSINVOICEID:
            setEbsInvoiceId((Number)value);
            return;
        case CLMPAYMENTHDRID:
            setClmPaymentHdrId((Number)value);
            return;
        case CLMINVOICELINENO:
            setClmInvoiceLineNo((Number)value);
            return;
        case FROMLOCATION:
            setFromLocation((String)value);
            return;
        case TOLOCATION:
            setToLocation((String)value);
            return;
        case ITEMKEY:
            setItemKey((String)value);
            return;
        case APPROVER1:
            setApprover1((String)value);
            return;
        case APPROVER2:
            setApprover2((String)value);
            return;
        case SAVEFLAG:
            setSaveFlag((String)value);
            return;
        case ERRORMSG:
            setErrorMsg((String)value);
            return;
        case CONCPROGRAMID:
            setConcProgramId((Number)value);
            return;
        case INVOICEHDRID:
            setInvoiceHdrId((Number)value);
            return;
        case INVPERIODFROMDATE:
            setInvPeriodFromDate((Date)value);
            return;
        case INVPERIODTODATE:
            setInvPeriodToDate((Date)value);
            return;
        case CIRCUITID:
            setCircuitId((String)value);
            return;
        case POUOM:
            setPoUom((String)value);
            return;
        case POTAX:
            setPoTax((Number)value);
            return;
        case ITEMCODE:
            setItemCode((String)value);
            return;
        case SUPPLIER:
            setSupplier((String)value);
            return;
        case SUPPLIERSITE:
            setSupplierSite((String)value);
            return;
        case ITEMID:
            setItemId((Number)value);
            return;
        case ITEMTYPE:
            setItemType((String)value);
            return;
        case VENDORID:
            setVendorId((Number)value);
            return;
        case VENDORSITEID:
            setVendorSiteId((Number)value);
            return;
        case POVALIDFROM:
            setPoValidFrom((Date)value);
            return;
        case POVALIDTO:
            setPoValidTo((Date)value);
            return;
        case COMMISSIONEDDATE:
            setCommissionedDate((Date)value);
            return;
        case CAPACITY:
            setCapacity((String)value);
            return;
        case CONVERSIONRATE:
            setConversionRate((Number)value);
            return;
        case CHARGEACCOUNT:
            setChargeAccount((String)value);
            return;
        case POAMOUNT:
            setPoAmount((Number)value);
            return;
        case POLINEAMOUNT:
            setPoLineAmount((Number)value);
            return;
        case AMOUNTPAID:
            setAmountPaid((Number)value);
            return;
        case BALAMT:
            setBalAmt((Number)value);
            return;
        case INVOICETYPE:
            setInvoiceType((String)value);
            return;
        case ADVPERIOD:
            setAdvPeriod((String)value);
            return;
        case ADVAMOUNT:
            setAdvAmount((Number)value);
            return;
        case ADVCURRENCY:
            setAdvCurrency((String)value);
            return;
        case ADVSUPINVOICENO:
            setAdvSupInvoiceNo((String)value);
            return;
        case ADVSUPINVOICEDATE:
            setAdvSupInvoiceDate((Date)value);
            return;
        case ADVVERIFIED:
            setAdvVerified((String)value);
            return;
        case ADVCREATEINVOICE:
            setAdvCreateInvoice((String)value);
            return;
        case ADVINVOICENO:
            setAdvInvoiceNo((String)value);
            return;
        case ACTIVITY:
            setActivity((String)value);
            return;
        case LINKTYPE:
            setLinkType((String)value);
            return;
        case SURRENDEREDDATE:
            setSurrenderedDate((Date)value);
            return;
        case PROCOMMISSIONEDDATE:
            setProCommissionedDate((Date)value);
            return;
        case REMARKS:
            setRemarks((String)value);
            return;
        case DISTCODECOMBINATIONID:
            setDistCodeCombinationId((Number)value);
            return;
        case ADVTAXPERCENT:
            setAdvTaxPercent((Number)value);
            return;
        case FROMLOCSNO:
            setFromLocSno((Number)value);
            return;
        case TOLOCSNO:
            setToLocSno((Number)value);
            return;
        case ADVREMARKS:
            setAdvRemarks((String)value);
            return;
        case LASTINVOICEDATE:
            setLastInvoiceDate((Date)value);
            return;
        case FINALSTATUS:
            setFinalStatus((String)value);
            return;
        case CLMCREATIONDATE:
            setClmCreationDate((Date)value);
            return;
        case VENDORSITECURRENCYCODE:
            setVendorSiteCurrencyCode((String)value);
            return;
        case APPROVEDDATE:
            setApprovedDate((Date)value);
            return;
        case BWDISTANCE:
            setBwDistance((Number)value);
            return;
        case BANDWIDHREQNO:
            setBandWidhReqNo((String)value);
            return;
        case QTY:
            setQty((Number)value);
            return;
        case ADVSTATUS:
            setAdvStatus((String)value);
            return;
        case PAYMENTSTATUS:
            setPaymentStatus((String)value);
            return;
        case PAIDDATE:
            setPaidDate((Date)value);
            return;
        case PAYMENTDETAILS:
            setPaymentDetails((String)value);
            return;
        case PAYMENTID:
            setPaymentId((Number)value);
            return;
        case EBSPONUMBER:
            setEbsPoNumber((Number)value);
            return;
        case CLMPONUMBER:
            setClmPoNumber((Number)value);
            return;
        case EBSPOHEADERID:
            setEbsPoHeaderId((Number)value);
            return;
        case EBSPOLINEID:
            setEbsPoLineId((Number)value);
            return;
        case ITEMDESC:
            setItemDesc((String)value);
            return;
        case PAYMENTTERM:
            setPaymentTerm((String)value);
            return;
        case INVAMTREF:
            setInvAmtRef((Number)value);
            return;
        case BATCHNO:
            setBatchNo((Number)value);
            return;
        case CGSTTAXCODE:
            setCgstTaxCode((String)value);
            return;
        case SGSTTAXCODE:
            setSgstTaxCode((String)value);
            return;
        case IGSTTAXCODE:
            setIgstTaxCode((String)value);
            return;
        case CGSTTAXPER:
            setCgstTaxPer((Number)value);
            return;
        case SGSTTAXPER:
            setSgstTaxPer((Number)value);
            return;
        case IGSTTAXPER:
            setIgstTaxPer((Number)value);
            return;
        case CGSTTAXAMT:
            setCgstTaxAmt((Number)value);
            return;
        case SGSTTAXAMT:
            setSgstTaxAmt((Number)value);
            return;
        case IGSTTAXAMT:
            setIgstTaxAmt((Number)value);
            return;
        case STGBATCHID:
            setStgBatchId((Number)value);
            return;
        case INVOICETOLERANCE:
            setInvoiceTolerance((Number)value);
            return;
        case INVOICEPAYCYCLE:
            setInvoicePayCycle((Number)value);
            return;
        case INVOICECYCLESTATUS:
            setInvoiceCycleStatus((String)value);
            return;
        case REJECTIONREASON:
            setRejectionReason((String)value);
            return;
        case APPROVER1DATE:
            setApprover1Date((Date)value);
            return;
        case APPROVER2DATE:
            setApprover2Date((Date)value);
            return;
        case FILEID:
            setFileId((String)value);
            return;
        case ATTACHEDFILENAME:
            setAttachedFileName((String)value);
            return;
        case ATTACHEDFILE:
            setAttachedFile((BlobDomain)value);
            return;
        case CONTENTTYPE:
            setContenttype((String)value);
            return;
        case FACREATIONDATE:
            setFaCreationDate((Date)value);
            return;
        case FACREATEDBY:
            setFaCreatedBy((Number)value);
            return;
        case FALASTUPDATEDATE:
            setFaLastUpdateDate((Date)value);
            return;
        case FALASTUPDATEDBY:
            setFaLastUpdatedBy((Number)value);
            return;
        case FALASTUPDATELOGIN:
            setFaLastUpdateLogin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
