package oracle.apps.sfc.clm.PaymentApproval.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CLMSearchNewVORowImpl extends OAViewRowImpl {
    public static final int BANDWIDHREQID = 0;
    public static final int BANDWIDHREQNO = 1;
    public static final int CLMID = 2;
    public static final int PONUMBER = 3;
    public static final int CLMINVOICENUMBER = 4;
    public static final int INVOICEDATE = 5;
    public static final int INVOICEWFSTATUS = 6;
    public static final int INVTOTAL = 7;
    public static final int SUPPLIER = 8;
    public static final int INVOICETYPE = 9;
    public static final int FILEID = 10;
    public static final int ATTACHEDFILENAME = 11;
    public static final int ATTACHEDFILE = 12;
    public static final int CONTENTTYPE = 13;
    public static final int FACREATIONDATE = 14;
    public static final int FACREATEDBY = 15;
    public static final int FALASTUPDATEDATE = 16;
    public static final int FALASTUPDATELOGIN = 17;
    public static final int FALASTUPDATEDBY = 18;
    public static final int APPROVESELECTFLAG = 19;

    /**This is the default constructor (do not remove)
     */
    public CLMSearchNewVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute BandWidhReqId
     */
    public String getBandWidhReqId() {
        return (String) getAttributeInternal(BANDWIDHREQID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BandWidhReqId
     */
    public void setBandWidhReqId(String value) {
        setAttributeInternal(BANDWIDHREQID, value);
    }

    /**Gets the attribute value for the calculated attribute BandWidhReqNo
     */
    public String getBandWidhReqNo() {
        return (String) getAttributeInternal(BANDWIDHREQNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BandWidhReqNo
     */
    public void setBandWidhReqNo(String value) {
        setAttributeInternal(BANDWIDHREQNO, value);
    }

    /**Gets the attribute value for the calculated attribute ClmId
     */
    public Number getClmId() {
        return (Number) getAttributeInternal(CLMID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ClmId
     */
    public void setClmId(Number value) {
        setAttributeInternal(CLMID, value);
    }

    /**Gets the attribute value for the calculated attribute PoNumber
     */
    public String getPoNumber() {
        return (String) getAttributeInternal(PONUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoNumber
     */
    public void setPoNumber(String value) {
        setAttributeInternal(PONUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute ClmInvoiceNumber
     */
    public String getClmInvoiceNumber() {
        return (String) getAttributeInternal(CLMINVOICENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ClmInvoiceNumber
     */
    public void setClmInvoiceNumber(String value) {
        setAttributeInternal(CLMINVOICENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceDate
     */
    public Date getInvoiceDate() {
        return (Date) getAttributeInternal(INVOICEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceDate
     */
    public void setInvoiceDate(Date value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceWfStatus
     */
    public String getInvoiceWfStatus() {
        return (String) getAttributeInternal(INVOICEWFSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceWfStatus
     */
    public void setInvoiceWfStatus(String value) {
        setAttributeInternal(INVOICEWFSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute InvTotal
     */
    public Number getInvTotal() {
        return (Number) getAttributeInternal(INVTOTAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvTotal
     */
    public void setInvTotal(Number value) {
        setAttributeInternal(INVTOTAL, value);
    }

    /**Gets the attribute value for the calculated attribute Supplier
     */
    public String getSupplier() {
        return (String) getAttributeInternal(SUPPLIER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Supplier
     */
    public void setSupplier(String value) {
        setAttributeInternal(SUPPLIER, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceType
     */
    public String getInvoiceType() {
        return (String) getAttributeInternal(INVOICETYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceType
     */
    public void setInvoiceType(String value) {
        setAttributeInternal(INVOICETYPE, value);
    }

    /**Gets the attribute value for the calculated attribute FileId
     */
    public String getFileId() {
        return (String) getAttributeInternal(FILEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FileId
     */
    public void setFileId(String value) {
        setAttributeInternal(FILEID, value);
    }

    /**Gets the attribute value for the calculated attribute AttachedFileName
     */
    public String getAttachedFileName() {
        return (String) getAttributeInternal(ATTACHEDFILENAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AttachedFileName
     */
    public void setAttachedFileName(String value) {
        setAttributeInternal(ATTACHEDFILENAME, value);
    }

    /**Gets the attribute value for the calculated attribute AttachedFile
     */
    public BlobDomain getAttachedFile() {
        return (BlobDomain) getAttributeInternal(ATTACHEDFILE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AttachedFile
     */
    public void setAttachedFile(BlobDomain value) {
        setAttributeInternal(ATTACHEDFILE, value);
    }

    /**Gets the attribute value for the calculated attribute Contenttype
     */
    public String getContenttype() {
        return (String) getAttributeInternal(CONTENTTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Contenttype
     */
    public void setContenttype(String value) {
        setAttributeInternal(CONTENTTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute FaCreationDate
     */
    public Date getFaCreationDate() {
        return (Date) getAttributeInternal(FACREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaCreationDate
     */
    public void setFaCreationDate(Date value) {
        setAttributeInternal(FACREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute FaCreatedBy
     */
    public Number getFaCreatedBy() {
        return (Number) getAttributeInternal(FACREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaCreatedBy
     */
    public void setFaCreatedBy(Number value) {
        setAttributeInternal(FACREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute FaLastUpdateDate
     */
    public Date getFaLastUpdateDate() {
        return (Date) getAttributeInternal(FALASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaLastUpdateDate
     */
    public void setFaLastUpdateDate(Date value) {
        setAttributeInternal(FALASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute FaLastUpdateLogin
     */
    public Number getFaLastUpdateLogin() {
        return (Number) getAttributeInternal(FALASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaLastUpdateLogin
     */
    public void setFaLastUpdateLogin(Number value) {
        setAttributeInternal(FALASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute FaLastUpdatedBy
     */
    public Number getFaLastUpdatedBy() {
        return (Number) getAttributeInternal(FALASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaLastUpdatedBy
     */
    public void setFaLastUpdatedBy(Number value) {
        setAttributeInternal(FALASTUPDATEDBY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case BANDWIDHREQID:
            return getBandWidhReqId();
        case BANDWIDHREQNO:
            return getBandWidhReqNo();
        case CLMID:
            return getClmId();
        case PONUMBER:
            return getPoNumber();
        case CLMINVOICENUMBER:
            return getClmInvoiceNumber();
        case INVOICEDATE:
            return getInvoiceDate();
        case INVOICEWFSTATUS:
            return getInvoiceWfStatus();
        case INVTOTAL:
            return getInvTotal();
        case SUPPLIER:
            return getSupplier();
        case INVOICETYPE:
            return getInvoiceType();
        case FILEID:
            return getFileId();
        case ATTACHEDFILENAME:
            return getAttachedFileName();
        case ATTACHEDFILE:
            return getAttachedFile();
        case CONTENTTYPE:
            return getContenttype();
        case FACREATIONDATE:
            return getFaCreationDate();
        case FACREATEDBY:
            return getFaCreatedBy();
        case FALASTUPDATEDATE:
            return getFaLastUpdateDate();
        case FALASTUPDATELOGIN:
            return getFaLastUpdateLogin();
        case FALASTUPDATEDBY:
            return getFaLastUpdatedBy();
        case APPROVESELECTFLAG:
            return getapproveSelectFlag();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case BANDWIDHREQID:
            setBandWidhReqId((String)value);
            return;
        case BANDWIDHREQNO:
            setBandWidhReqNo((String)value);
            return;
        case CLMID:
            setClmId((Number)value);
            return;
        case PONUMBER:
            setPoNumber((String)value);
            return;
        case CLMINVOICENUMBER:
            setClmInvoiceNumber((String)value);
            return;
        case INVOICEDATE:
            setInvoiceDate((Date)value);
            return;
        case INVOICEWFSTATUS:
            setInvoiceWfStatus((String)value);
            return;
        case INVTOTAL:
            setInvTotal((Number)value);
            return;
        case SUPPLIER:
            setSupplier((String)value);
            return;
        case INVOICETYPE:
            setInvoiceType((String)value);
            return;
        case FILEID:
            setFileId((String)value);
            return;
        case ATTACHEDFILENAME:
            setAttachedFileName((String)value);
            return;
        case ATTACHEDFILE:
            setAttachedFile((BlobDomain)value);
            return;
        case CONTENTTYPE:
            setContenttype((String)value);
            return;
        case FACREATIONDATE:
            setFaCreationDate((Date)value);
            return;
        case FACREATEDBY:
            setFaCreatedBy((Number)value);
            return;
        case FALASTUPDATEDATE:
            setFaLastUpdateDate((Date)value);
            return;
        case FALASTUPDATELOGIN:
            setFaLastUpdateLogin((Number)value);
            return;
        case FALASTUPDATEDBY:
            setFaLastUpdatedBy((Number)value);
            return;
        case APPROVESELECTFLAG:
            setapproveSelectFlag((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute approveSelectFlag
     */
    public String getapproveSelectFlag() {
        return (String) getAttributeInternal(APPROVESELECTFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute approveSelectFlag
     */
    public void setapproveSelectFlag(String value) {
        setAttributeInternal(APPROVESELECTFLAG, value);
    }
}
