package oracle.apps.sfc.clm.PaymentApproval.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxsifyPaymentApprovalAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public xxsifyPaymentApprovalAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("oracle.apps.sfc.clm.PaymentApproval.server", /* package name */
      "xxsifyPaymentApprovalAMLocal" /* Configuration Name */);
    }


    /**Container's getter for CLMApprovalStatusLovVO
     */
    public CLMApprovalStatusLovVOImpl getCLMApprovalStatusLovVO() {
        return (CLMApprovalStatusLovVOImpl)findViewObject("CLMApprovalStatusLovVO");
    }

    /**Container's getter for CLMInvDetailsVO
     */
    public CLMInvDetailsVOImpl getCLMInvDetailsVO() {
        return (CLMInvDetailsVOImpl)findViewObject("CLMInvDetailsVO");
    }

    /**Container's getter for CLMSearchNewVO1
     */
    public CLMSearchNewVOImpl getCLMSearchNewVO1() {
        return (CLMSearchNewVOImpl)findViewObject("CLMSearchNewVO1");
    }

    /**Container's getter for CLMSearchVO
     */
    public CLMSearchVOImpl getCLMSearchVO() {
        return (CLMSearchVOImpl)findViewObject("CLMSearchVO");
    }
}
